### ISSUE TITLE
ReactJS library size issue

### ISSUE THREAD

**Issue by gitgunter** [hugeicons/hugeicons#1]
Hi, Recently, I installed the hugeicons-react library to test free icons, when I import the library, it has too much size even though it is only one icon that I am importing. When I run the `npm run build` command, the build is done with all the icons in the library.

JSX Component
![Screenshot 2024-02-21 133713](https://github.com/hugeicons/hugeicons-react/assets/73723099/643ee421-d9c9-475b-b3d0-14c6296ca83c)

Build log and vite.config.js file
![Screenshot 2024-02-21 133535](https://github.com/hugeicons/hugeicons-react/assets/73723099/89afb5aa-cf30-420e-815c-e31cc1798e18)

**Comment by xtawfik** [comment]
Hi, thanks for reporting this issue.
Our team will work on this, and release an update very soon.

Thanks for choosing Hugeicons.

**Comment by KingXP-Pythoner** [comment]
just changed from lucide-react to hugeicons-react and noticed really slow dev experience and 17k+ modules being compiled. Import cost also shows 10.6M (gzipped: 1M)

**Comment by railsfactory-robin** [comment]
I'm getting 3000 + warnings in my console like below

WARNING in ./node_modules/hugeicons-react/dist/WifiSignal/wifi-off-01.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/robin/projects/cvsqure/node_modules/hugeicons-react/icons/WifiSignal/wifi-off-01.tsx' file: Error: ENOENT: no such file or directory, open '/Users/robin/projects/cvsqure/node_modules/hugeicons-react/icons/WifiSignal/wifi-off-01.tsx'

WARNING in ./node_modules/hugeicons-react/dist/WifiSignal/wifi-unlock.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/robin/projects/cvsqure/node_modules/hugeicons-react/icons/WifiSignal/wifi-unlock.tsx' file: Error: ENOENT: no such file or directory, open '/Users/robin/projects/cvsqure/node_modules/hugeicons-react/icons/WifiSignal/wifi-unlock.tsx'

**Comment by hugeicons** [comment]
Please upgrade to the latest version 0.2.0, it is rewritten in typescript from scratch and should be working smoothly without issues.
