### ISSUE TITLE
Getting warnings after installing the package -  webpack compiled with 3908 warnings

### ISSUE THREAD

**Issue by railsfactory-robin** [hugeicons/hugeicons#2]
<img width="1631" alt="Screenshot 2024-04-05 at 11 58 21 PM" src="https://github.com/hugeicons/hugeicons-react/assets/13621635/50213c8d-b1e6-48b7-9455-7049f135a430">

WARNING in ./node_modules/hugeicons-react/dist/WifiSignal/wifi-off-01.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/robin/projects/cvsqure/node_modules/hugeicons-react/icons/WifiSignal/wifi-off-01.tsx' file: Error: ENOENT: no such file or directory, open '/Users/robin/projects/cvsqure/node_modules/hugeicons-react/icons/WifiSignal/wifi-off-01.tsx'

same like above im getting lots of warnings, how can i remove the warning?

**Comment by hugeicons** [comment]
Please upgrade to the latest version 0.2.0, it is rewritten in typescript from scratch and should be working smoothly without issues.
