### ISSUE TITLE
current version is breaking NextJS builds

### ISSUE THREAD

**Issue by 0tii** [hugeicons/hugeicons#5]
Its quite bad to be honest, the current version `0.2.0` is breaking NextJs builds.

Its enough to import a single icon and the builds will fail.

After removing all icons and the package the builds returned to working as normal. Its been a big waste of time

**Comment by hugeicons** [comment]
Hello there,

We’ve updated all the icons as well as the code. It’s tested in Next.js, and it should work fine now.
