### ISSUE TITLE
Are the "rotate" and "animation" APIs supported in hugeicons-react?

### ISSUE THREAD

**Issue by glin7976** [hugeicons/hugeicons#6]
I just copied the sample code and found "rotate" and "animation" are not working.
` <ListSettingIcon rotate={90}/>
  <MarketingIcon animate={true}/>`
  
  package: hugeicons-react
  version: 0.2.0

**Comment by hugeicons** [comment]
Hello there,

Currently, it doesn’t support animations and rotation. We have removed the sample code. We hope to implement it soon. Are you still finding this code anywhere?

**Comment by mcnaveen** [comment]
> **Are you still finding this code anywhere?**
In your NPM docs

![qkXIJK5iaBo1KrlkbIcDsjEe@2x](https://github.com/user-attachments/assets/de4d6f62-a7cc-490d-8e18-921d6f494ef2)
