### ISSUE TITLE
Missing standard type in CheckmarkSquare04Icon

### ISSUE THREAD

**Issue by OferLahav2** [hugeicons/hugeicons#8]
The React library <CheckmarkSquare04Icon /> is missing the `standard` `type`. It is in the docs but not implementable.
<img width="369" alt="Screenshot 2024-07-25 at 8 36 58 PM" src="https://github.com/user-attachments/assets/2a4e7960-190b-446c-8ad7-833c292c0e5e">

If we don't specify the type we see the `rounded` type by default.

**Comment by hugeicons** [comment]
Hello there, this is our free pack, and it contains only stroke-rounded type. All other icons are available in premium packages.
